version: "3.7"

services:
  log_writer:
    build: .
    volumes:
      - .:/usr/src/app
    command: ["pipenv", "run", "log"]

  log_monitor:
    build: .
    volumes:
      - .:/usr/src/app
    command: ["pipenv", "run", "smoketest"]
